# no manual edits - this file is autogenerated by dmake

INCLUDEPATH += ../externals/tinyxml


SOURCES += $${BASEPATH}/test64bit.cpp \
           $${BASEPATH}/testassert.cpp \
           $${BASEPATH}/testautovariables.cpp \
           $${BASEPATH}/testbool.cpp \
           $${BASEPATH}/testboost.cpp \
           $${BASEPATH}/testbufferoverrun.cpp \
           $${BASEPATH}/testcharvar.cpp \
           $${BASEPATH}/testclass.cpp \
           $${BASEPATH}/testcmdlineparser.cpp \
           $${BASEPATH}/testcondition.cpp \
           $${BASEPATH}/testconstructors.cpp \
           $${BASEPATH}/testcppcheck.cpp \
           $${BASEPATH}/testerrorlogger.cpp \
           $${BASEPATH}/testexceptionsafety.cpp \
           $${BASEPATH}/testfilelister.cpp \
           $${BASEPATH}/testgarbage.cpp \
           $${BASEPATH}/testincompletestatement.cpp \
           $${BASEPATH}/testinternal.cpp \
           $${BASEPATH}/testio.cpp \
           $${BASEPATH}/testleakautovar.cpp \
           $${BASEPATH}/testlibrary.cpp \
           $${BASEPATH}/testmathlib.cpp \
           $${BASEPATH}/testmemleak.cpp \
           $${BASEPATH}/testnonreentrantfunctions.cpp \
           $${BASEPATH}/testnullpointer.cpp \
           $${BASEPATH}/testobsolescentfunctions.cpp \
           $${BASEPATH}/testoptions.cpp \
           $${BASEPATH}/testother.cpp \
           $${BASEPATH}/testpath.cpp \
           $${BASEPATH}/testpathmatch.cpp \
           $${BASEPATH}/testpostfixoperator.cpp \
           $${BASEPATH}/testpreprocessor.cpp \
           $${BASEPATH}/testrunner.cpp \
           $${BASEPATH}/testsamples.cpp \
           $${BASEPATH}/testsimplifytemplate.cpp \
           $${BASEPATH}/testsimplifytokens.cpp \
           $${BASEPATH}/testsimplifytypedef.cpp \
           $${BASEPATH}/testsizeof.cpp \
           $${BASEPATH}/teststl.cpp \
           $${BASEPATH}/teststring.cpp \
           $${BASEPATH}/testsuite.cpp \
           $${BASEPATH}/testsuppressions.cpp \
           $${BASEPATH}/testsymboldatabase.cpp \
           $${BASEPATH}/testthreadexecutor.cpp \
           $${BASEPATH}/testtimer.cpp \
           $${BASEPATH}/testtoken.cpp \
           $${BASEPATH}/testtokenize.cpp \
           $${BASEPATH}/testtype.cpp \
           $${BASEPATH}/testuninitvar.cpp \
           $${BASEPATH}/testunusedfunctions.cpp \
           $${BASEPATH}/testunusedprivfunc.cpp \
           $${BASEPATH}/testunusedvar.cpp \
           $${BASEPATH}/testvaarg.cpp \
           $${BASEPATH}/testvalueflow.cpp \
           $${BASEPATH}/testvarid.cpp
