exclude_paths:
  - addons/test/*.c
  - addons/test/*.cpp
  - addons/y2038/test/*.c
  - htmlreport/example.cc
  - samples/**/bad.c
  - samples/**/bad.cpp
  - test/test.cxx
  - test/cfg/*.c
  - test/cfg/*.cpp
  - test/synthetic/*.c
