#!/bin/bash
make clean
rm -r coverage_report
make test CXXFLAGS="-Wall -Wextra -pedantic -g -fprofile-arcs -ftest-coverage"
gcov lib/*.cpp -o lib/
lcov --directory ./ --capture --output-file lcov.info -b ./
genhtml lcov.info -o coverage_report
rm lib/*.gcda
rm lib/*.gcno
rm test/*.gcda
rm test/*.gcno
rm lcov.info
make clean
