#!/bin/bash

astyle --style=ansi --min-conditional-indent=0 cli/*.cpp
astyle --style=ansi --min-conditional-indent=0 cli/*.h
astyle --style=ansi --min-conditional-indent=0 gui/*.cpp
astyle --style=ansi --min-conditional-indent=0 gui/*.h
astyle --style=ansi --min-conditional-indent=0 lib/*.cpp
astyle --style=ansi --min-conditional-indent=0 lib/*.h
astyle --style=ansi --min-conditional-indent=0 test/*.cpp
astyle --style=ansi --min-conditional-indent=0 test/*.h

astyle --style=ansi --min-conditional-indent=0 tools/*.cpp

