if (MSVC)
    # Visual Studio only sets _DEBUG
    if (CMAKE_BUILD_TYPE MATCHES "Debug")
        add_definitions(-DDEBUG)
    endif()
endif()
if (UNIX)
    if (CMAKE_BUILD_TYPE MATCHES "Debug")
        add_definitions(-D_GLIBCXX_DEBUG)
    endif()
    if (HAVE_RULES)
        add_definitions(-DHAVE_RULES -DTIXML_USE_STL)
    endif()
    if (USE_Z3)
        add_definitions(-DUSE_Z3 -DNEW_Z3)
    endif()
    add_definitions(-DFILESDIR="${FILESDIR}")
endif()
if (ENABLE_CHECK_INTERNAL)
    add_definitions(-DCHECK_INTERNAL)
endif()
