if (UNIX)
    if (${CMAKE_BUILD_TYPE} STREQUAL "Debug")
        add_definitions(-D_GLIBCXX_DEBUG)
    endif()
    if (HAVE_RULES)
        add_definitions(-DHAVE_RULES -DTIXML_USE_STL)
    endif()
    add_definitions(-DCFGDIR="${CMAKE_INSTALL_PREFIX}/share/cppcheck")
elseif (WIN32)
    add_definitions(-D_CRT_SECURE_NO_WARNINGS)
    add_definitions(-DWIN32_LEAN_AND_MEAN)
endif()
