if(ANALYZE_MEMORY)
    add_compile_options(-fsanitize=memory)
    add_compile_options(-fsanitize-memory-track-origins=2)
    add_compile_options(-fno-omit-frame-pointer)
    # NOTE: tail call elimination -fno-optimize-sibling-calls
elseif(ANALYZE_ADDRESS)
    add_compile_options(-fsanitize=address)
    add_compile_options(-fno-omit-frame-pointer)
elseif(ANALYZE_THREAD)
    add_compile_options(-fsanitize=thread)
endif()

if(ANALYZE_UNDEFINED)
    add_compile_options(-fsanitize=undefined-trap)
    add_compile_options(-fsanitize-undefined-trap-on-error)
    add_compile_options(-fno-sanitize-recover)
endif()

if(ANALYZE_DATAFLOW)
    add_compile_options(-fsanitize=dataflow)
endif()
