MESSAGE( STATUS "------------------ General configuration for ${PROJECT_NAME} ${VERSION} -----------------")
MESSAGE( STATUS )
MESSAGE( STATUS "CMake Generator:            ${CMAKE_GENERATOR}")
MESSAGE( STATUS "Compiler:                   ${CMAKE_CXX_COMPILER_ID}")
MESSAGE( STATUS "Build type:                 ${CMAKE_BUILD_TYPE}")
MESSAGE( STATUS "C++ flags (General):        ${CMAKE_CXX_FLAGS}")
MESSAGE( STATUS "C++ flags (Release):        ${CMAKE_CXX_FLAGS_RELEASE}")
MESSAGE( STATUS "C++ flags (Debug):          ${CMAKE_CXX_FLAGS_DEBUG}")
MESSAGE( STATUS )
MESSAGE( STATUS "---------------------------------------------------------" )
MESSAGE( STATUS "USE_CLANG =                 ${USE_CLANG}" )
MESSAGE( STATUS "USE_ANALYZE =               ${USE_ANALYZE}" )
MESSAGE( STATUS "ANALYZE_MEMORY =            ${ANALYZE_MEMORY}" )
MESSAGE( STATUS "ANALYZE_ADDRESS =           ${ANALYZE_ADDRESS}" )
MESSAGE( STATUS "ANALYZE_THREAD =            ${ANALYZE_THREAD}" )
MESSAGE( STATUS "ANALYZE_UNDEFINED =         ${ANALYZE_UNDEFINED}" )
MESSAGE( STATUS "ANALYZE_DATAFLOW =          ${ANALYZE_DATAFLOW}" )
MESSAGE( STATUS "BUILD_SHARED_LIBS =         ${BUILD_SHARED_LIBS}" )
MESSAGE( STATUS "BUILD_TESTS =               ${BUILD_TESTS}" )
MESSAGE( STATUS "BUILD_QT_APP =              ${BUILD_QT_APP}" )
MESSAGE( STATUS "WARNINGS_ANSI_ISO =         ${WARNINGS_ANSI_ISO}" )
MESSAGE( STATUS "WARNINGS_ARE_ERRORS =       ${WARNINGS_ARE_ERRORS}" )
MESSAGE( STATUS "CMAKE_INSTALL_PREFIX =      ${CMAKE_INSTALL_PREFIX}" )
MESSAGE( STATUS )
MESSAGE( STATUS "Change a value with: cmake -D<Variable>=<Value>" )
MESSAGE( STATUS )
IF(${USE_ANALYZE})
   MESSAGE( STATUS "------------------- Run static analyzer ----------------------" )
   MESSAGE( STATUS "##############################")
   MESSAGE( STATUS "RUN: scan-build make" )
   MESSAGE( STATUS "##############################")
   MESSAGE( STATUS )
ENDIF()

IF(${ANALYZE_ADDRESS})
   MESSAGE("##########################################################")
   MESSAGE(STATUS "For better visualitation change enviroment variable: ASAN_SYMBOLIZER_PATH=/path/to/llvm-symbolizer")
   MESSAGE(STATUS "Detect memory leaks, change enviroment variable: ASAN_OPTIONS=\"detect_leaks=1\"")
   MESSAGE("##########################################################")
ENDIF()
