# Version for libraries CPP
SET(VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
SET(VERSION_MINOR ${PROJECT_VERSION_MINOR})
SET(VERSION_PATCH ${PROJECT_VERSION_PATCH})
SET(SOVERSION "${VERSION_MAJOR}.${VERSION_MINOR}")

# Postfix of so's:
SET(DLLVERSION "")
SET(DEBUG_POSTFIX "")
