name:               cppcheckgui
version:            'todo'
summary:            todo
description:        |
  todo
grade:              stable
confinement:        devmode
icon:               snap/gui/cppcheck-gui.png
type:               app

apps:
  cppcheckgui:
    command:        desktop-launch ${SNAP}/bin/cppcheck-gui
    plugs:          [home, unity7, x11, camera,network-bind, network-control, account-control]

# TODO(gocarlos):   check if all those dependencies are needed.
parts:
  cppcheckgui:
    source-type:    git
    plugin:         cmake
    configflags:
      - -DBUILD_GUI=ON
    after:          [desktop-qt5]
    build-packages:
      # A list of Ubuntu packages to be installed on the host to aid in building the part.
      # These packages will not go into the final snap.
      - build-essential
      - qt5-default
      - qtbase5-dev
  desktop-qt5:
    stage-packages:
      # A set of Ubuntu packages to be downloaded and unpacked to join the part before it’s built.
      # Note that these packages are not installed on the host. Like the rest of the part, all files from these packages will make it into the final snap unless filtered out via the prime keyword.
      - libqt5gui5
      - libqt5svg5 # for loading icon themes which are svg
      - libtiff5-dev
      - libjpeg8-dev
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - shared-mime-info
      - libgdk-pixbuf2.0-0
      - locales-all
