
all:	controlflow.o	data.o	functions.o	uninit.o

controlflow.o:	controlflow.c
	gcc -c controlflow.c

data.o:	data.c
	gcc -c data.c

functions.o:	functions.c
	gcc -c functions.c

uninit.o:	uninit.c
	gcc -std=gnu99 -c uninit.c
