# Syntax reference https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
# Environment reference https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
name: CI-unixish

on:
  push:
    branches:
      - 'main'
      - 'releases/**'
      - '2.*'
    tags:
      - '2.*'
  pull_request:

permissions:
  contents: read

jobs:

  build_cmake:

    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-13]
        include:
          - use_qt6: On
          - os: ubuntu-20.04
            use_qt6: Off
      fail-fast: false # Prefer quick result

    runs-on: ${{ matrix.os }}

    env:
      # TODO: figure out why there are cache misses with PCH enabled
      CCACHE_SLOPPINESS: pch_defines,time_macros

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.workflow }}-${{ github.job }}-${{ matrix.os }}

      - name: Install missing software on ubuntu
        if: contains(matrix.os, 'ubuntu') && matrix.use_qt6 == 'Off'
        run: |
          sudo apt-get update
          sudo apt-get install libxml2-utils qtbase5-dev qttools5-dev libqt5charts5-dev qtchooser

      # TODO: move latest compiler to separate step
      # TODO: bail out on warnings with latest GCC
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        if: false  # matrix.os == 'ubuntu-22.04'
        with:
          version: 13
          platform: x64

      - name: Select compiler
        if: false  # matrix.os == 'ubuntu-22.04'
        run: |
          echo "CXX=g++-13" >> $GITHUB_ENV

      - name: Install missing software on ubuntu
        if: contains(matrix.os, 'ubuntu') && matrix.use_qt6 == 'On'
        run: |
          sudo apt-get update
          sudo apt-get install libxml2-utils
          # qt6-tools-dev-tools for lprodump
          # qt6-l10n-tools for lupdate
          sudo apt-get install qt6-base-dev libqt6charts6-dev qt6-tools-dev qt6-tools-dev-tools qt6-l10n-tools libglx-dev libgl1-mesa-dev

      # coreutils contains "nproc"
      - name: Install missing software on macos
        if: contains(matrix.os, 'macos')
        run: |
          # pcre was removed from runner images in November 2022
          brew install coreutils qt@6 pcre

      - name: CMake build on ubuntu (with GUI)
        if: contains(matrix.os, 'ubuntu')
        run: |
          cmake -S . -B cmake.output -G "Unix Makefiles" -DHAVE_RULES=On -DBUILD_TESTS=On -DBUILD_GUI=On -DUSE_QT6=${{ matrix.use_qt6 }} -DWITH_QCHART=On -DCMAKE_DISABLE_PRECOMPILE_HEADERS=On -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          cmake --build cmake.output -- -j$(nproc)

      - name: CMake build on macos (with GUI)
        if: contains(matrix.os, 'macos')
        run: |
          cmake -S . -B cmake.output -G "Unix Makefiles" -DHAVE_RULES=On -DBUILD_TESTS=On -DBUILD_GUI=On -DUSE_QT6=On -DWITH_QCHART=On -DCMAKE_DISABLE_PRECOMPILE_HEADERS=On -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DQt6_DIR=$(brew --prefix qt@6)/lib/cmake/Qt6
          cmake --build cmake.output -- -j$(nproc)

      - name: Run CMake test
        run: |
          cmake --build cmake.output --target check -- -j$(nproc)

      - name: Run CTest
        run: |
          pushd cmake.output
          ctest --output-on-failure -j$(nproc)
