# Syntax reference https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
# Environment reference https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
name: cppcheck-premium

on:
  push:
    branches:
      - 'main'
      - 'releases/**'
      - '2.*'
    tags:
      - '2.*'
  pull_request:
  workflow_dispatch:
    inputs:
      premium_version:
        description: 'Cppcheck Premium version'

permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-24.04 # run on the latest image only
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Download cppcheckpremium
        run: |
          wget https://files.cppchecksolutions.com/devdrop/cppcheckpremium-devdrop-20250710-amd64.tar.gz -O cppcheckpremium.tar.gz
          tar xzvf cppcheckpremium.tar.gz
          mv cppcheckpremium-devdrop-20250710 cppcheckpremium

      - name: Generate a license file
        run: |
          mkdir ~/.cppcheckpremium
          echo d6dd5 > ~/.cppcheckpremium/cppcheck-premium-git.lic
          echo 260426 >> ~/.cppcheckpremium/cppcheck-premium-git.lic
          echo abdc6437a51ed209 >> ~/.cppcheckpremium/cppcheck-premium-git.lic
          echo 559f05803f67ce4c >> ~/.cppcheckpremium/cppcheck-premium-git.lic

      - name: Check
        run: |
          cppcheckpremium/cppcheck --premium=safety-off -j$(nproc) -D__GNUC__ -D__CPPCHECK__ --suppressions-list=cppcheckpremium-suppressions --platform=unix64 --enable=style --premium=misra-c++-2023 --premium=cert-c++-2016 --inline-suppr lib --error-exitcode=0 --output-format=sarif 2> results.sarif

      - name: Cat results
        run: |
          cat results.sarif
          sed -i 's|"startColumn": 0,|"startColumn": 1,|' results.sarif
          sed -i 's|"endColumn": 0,|"endColumn": 1,|' results.sarif

      - name: Upload report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
