
name: selfcheck-premium

on:
  push:
    branches:
      - 'main'
      - 'releases/**'
    tags:
      - '2.*'
  pull_request:

permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-22.04 # run on the latest image only

    env:
      PREMIUM_VERSION: devdrop-20231104

    steps:
      - uses: actions/checkout@v3

      - name: Download cppcheckpremium
        run: |
          wget https://files.cppchecksolutions.com/cppcheckpremium-devdrop-20231104-amd64.tar.gz
          tar xzvf cppcheckpremium-devdrop-20231104-amd64.tar.gz

      - name: Generate a license file
        run: |
          echo cppcheck > cppcheck.lic
          echo 231231 >> cppcheck.lic
          echo 80000 >> cppcheck.lic
          echo 57e08c39523ab54d >> cppcheck.lic
          echo path:lib >> cppcheck.lic

      - name: Self check
        run: |
          cppcheckpremium-devdrop-20231104/premiumaddon --check-loc-license cppcheck.lic > cppcheck-premium-loc
          cppcheckpremium-devdrop-20231104/cppcheck -D__GNUC__ -D__CPPCHECK__ --suppressions-list=cppcheckpremium-suppressions --platform=unix64 --enable=style --premium=misra-c++-2008 --premium=cert-c++-2016 lib
