# Syntax reference https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
# Environment reference https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
name: cppcheck-premium

on:
  push:
    branches:
      - 'main'
      - 'releases/**'
    tags:
      - '2.*'
  pull_request:
  workflow_dispatch:
    inputs:
      premium_version:
        description: 'Cppcheck Premium version'

permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-24.04 # run on the latest image only
    steps:
      - uses: actions/checkout@v4

      - name: Download cppcheckpremium
        run: |
          premium_version=${{ inputs.premium_version }}
          if [ -z $premium_version ]; then
            premium_version=24.9.0.1
            #wget https://files.cppchecksolutions.com/devdrop/cppcheckpremium-$premium_version-amd64.tar.gz -O cppcheckpremium.tar.gz
            wget https://files.cppchecksolutions.com/$premium_version/ubuntu-24.04/cppcheckpremium-$premium_version-amd64.tar.gz -O cppcheckpremium.tar.gz
          else
            wget https://files.cppchecksolutions.com/$premium_version/ubuntu-24.04/cppcheckpremium-$premium_version-amd64.tar.gz -O cppcheckpremium.tar.gz
          fi
          tar xvzf cppcheckpremium.tar.gz
          mv cppcheckpremium-$premium_version cppcheckpremium

      - name: Generate a license file
        run: |
          echo cppcheck > cppcheck.lic
          echo 241231 >> cppcheck.lic
          echo 80000 >> cppcheck.lic
          echo 53b72a908d7aeeee >> cppcheck.lic
          echo path:lib >> cppcheck.lic

      - name: Check
        run: |
          cppcheckpremium/premiumaddon --check-loc-license cppcheck.lic > cppcheck-premium-loc
          cppcheckpremium/cppcheck -j$(nproc) -D__GNUC__ -D__CPPCHECK__ --suppressions-list=cppcheckpremium-suppressions --platform=unix64 --enable=style --premium=misra-c++-2023 --premium=cert-c++-2016 --inline-suppr --error-exitcode=1 lib
