name: "IRC Push Notification"
on: [pull_request, create]

jobs:
  test:
    if: github.repository == 'danmar/cppcheck'
    runs-on: ubuntu-20.04
    steps:
      - name: irc pull request
        uses: rectalogic/notify-irc@v1
        if: github.event_name == 'pull_request'
        with:
          channel: "#cppcheck"
          nickname: cppcheck-github-notifier
          message: |
            ${{ github.actor }} opened PR ${{ github.event.html_url }}
      - name: irc tag created
        uses: rectalogic/notify-irc@v1
        if: github.event_name == 'create' && github.event.ref_type == 'tag'
        with:
          channel: "#cppcheck"
          nickname: cppcheck-github-notifier
          message: |
            ${{ github.actor }} tagged ${{ github.repository }} ${{ github.event.ref }}
